# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Bio
    url: /
    weight: 10
  - name: Curriculum
    url: experience/
    weight: 20
  - name: Publications
    url: /#papers
    weight: 30
#  - name: Projects
#    url: projects/
#   weight: 40

